"""
Django settings for Blog project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm#z!*6@gh7tt%cyx2atxz8(i=391br^mhehq9u@iilmghyy+xj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',         # 注册xadmin
    'crispy_forms',   # 注册crispy_forms
    'reversion',
    'DjangoUeditor',  # 百度的html编辑器
    # 'haystack',     # 注册全文检索
    'social_django',  # 第三登录
    'apps.blog',           # 注册博客应用
    'apps.user',           # 用户模块
    'raven.contrib.django.raven_compat',  # 注册sentry
]

MIDDLEWARE_CLASSES = (
    'raven.contrib.django.raven_compat.middleware.Sentry404CatchMiddleware',  # 启用sentry404中间件
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "utils.middleware.UrlPathRecordMiddleware",  # 注册记录用户访问地址中间件类
    "utils.middleware.ExceptionMiddleware",
)

ROOT_URLCONF = 'Blog.urls'

# 设置静态文件路径
STATIC_URL = 'apps/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'apps/static')]
STATIC_ROOT = '/var/www/Blog/static/'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'apps/templates')],  # 设置模板路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'Blog.wsgi.application'

HAYSTACK_CONNECTIONS = {
    'default': {
        # 使用whoosh引擎
        'ENGINE': "haystack.backends.whoosh_cn_backend.WhooshEngine",
        # 索引文件路径
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    }
}

# 当添加,修改,删除数据时,自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

HAYSTACK_SEARCH_RESULTS_PER_PAGE = 3  # 指定搜索结果页每页显示多少条信息

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Blog',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '809588434',
        'HOST': 'localhost',
        # 'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        # }
    }
}


# 指定认证后端
AUTHENTICATION_BACKENDS = (
    "social_core.backends.weibo.WeiboOAuth2",
    'django.contrib.auth.backends.ModelBackend',
)

# 配置第三方登录的App Secret和key
SOCIAL_AUTH_WEIBO_KEY = '3313597197'
SOCIAL_AUTH_WEIBO_SECRET = '344ce25907c473a43928dbb7b1fa8c27'

# 用户登录成功后进行跳转
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'

# 使用用户名来创建实例
SOCIAL_AUTH_WEIBO_DOMAIN_AS_USERNAME = True


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'  # 中国语言
TIME_ZONE = 'Asia/Shanghai'  # 上海时间
USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


# 配置Broker
BROKER_URL = 'redis://127.0.0.1:6379/0'
BROKER_TRANSPORT = 'redis'


# 发送邮件配置
EMAIL_USE_SSL = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465
EMAIL_TIMEOUT = 3600  # 设置超时时间
EMAIL_HOST_USER = '17610898052@163.com'  # 发送邮件的邮箱
EMAIL_HOST_PASSWORD = 'linsijian233'  # 在邮箱中设置的客户端授权密码
EMAIL_FROM = '起風了<17610898052@163.com>'  # 收件人看到的发件人

import raven

# sentry设置
RAVEN_CONFIG = {
    'dsn': 'https://ed7ffcd3d1df4d77be9b17746db3c9da:448d01df93ad41e7ba4cef4d15534d6d@sentry.io/249065'
}

from raven.contrib.django.raven_compat.models import client
client.captureException()

# WSGI中间件
from raven.contrib.django.raven_compat.middleware.wsgi import Sentry
from django.core.wsgi import get_wsgi_application

application = Sentry(get_wsgi_application())


import logging
import django.utils.log
import logging.handlers


LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,

    'root': {
        'level': 'WARNING',
        'handlers': ['sentry'],
    },


    # 配置打印日志格式
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s]- %(message)s'}
    },

    """
    格式             描述
    %(name)s	    记录器的名称
    %(levelno)s	    数字形式的日志记录级别
    %(levelname)s	日志记录级别的文本名称
    %(filename)s	执行日志记录调用的源文件的文件名称
    %(pathname)s	执行日志记录调用的源文件的路径名称
    %(funcName)s	执行日志记录调用的函数名称
    %(module)s	    执行日志记录调用的模块名称
    %(lineno)s	    执行日志记录调用的行号
    %(created)s	    执行日志记录的时间
    %(asctime)s	    日期和时间
    %(msecs)s	    毫秒部分
    %(thread)d	    线程ID
    %(threadName)s	线程名称
    %(process)d	    进程ID
    %(message)s	    记录的消息
    """

    'filters': {
    },

    # 定义具体处理日志的方式
    'handlers': {
        'sentry': {
            'level': 'ERROR', # To capture more than ERROR, change to WARNING, INFO, etc.
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
            'tags': {'custom-tag': 'x'},
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/project/Blog/log/all.log',  # 日志输出文件
            'maxBytes': 1024 * 1024 * 5,  # 文件大小
            'backupCount': 5,  # 备份份数
            'formatter': 'standard',  # 使用哪种formatters日志格式
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/project/Blog/log/error.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'request_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/project/Blog/log/script.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'scprits_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/project/Blog/log/script.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'standard',
        }
    },

    # 1.loggers类型为"django"这将处理所有类型日志。
    # 2.sourceDns.webdns.views 应用的py文件
    'loggers': {
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['console'],
            'propagate': False,
        },
        'raven': {
            'level': 'INFO',
            'handlers': ['console'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'INFO',
            'handlers': ['console'],
            'propagate': False,
        },
        'django': {
            'handlers': ['default', 'console'],
            'level': 'INFO',
            'propagate': False
        },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'scripts': {
            'handlers': ['scprits_handler'],
            'level': 'INFO',
            'propagate': False
        },
        'sourceDns.webdns.views': {
            'handlers': ['default', 'error'],
            'level': 'INFO',
            'propagate': True
        },
        'sourceDns.webdns.util': {
            'handlers': ['error'],
            'level': 'ERROR',
            'propagate': True
        }
    }
}
